#  TODO: FIX This all node behaviour -> check if it's a Foxy issue
# /**/differential_flatness_controller: 
/**:
  ros__parameters:
    uav_mass: 0.75
    antiwindup_cte : 5.0
    alpha: 0.1
    trajectory_following:
      position_Kp:
        x: 6.0
        y: 6.0
        z: 6.0
      position_Ki:
        x: 0.05
        y: 0.05
        z: 0.065
      position_Kd:
        x: 2.5
        y: 2.5
        z: 3.0
    speed_following:
      speed_Kp: 
        x: 2.8
        y: 2.8
        z: 4.0
      speed_Kd: 
        x: 0.008
        y: 0.008
        z: 0.0
      speed_Ki:
        x: 1.6
        y: 1.6
        z: 0.1
    angular_speed_controller:
      angular_gain:
        x: 5.5
        y: 5.5
        z: 2.0 